/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.utp.misiontic2022.andreslondono.view.gui;

import javax.swing.JPanel;

/**
 *
 * @author Andres
 */
public class FrmPrincipal extends javax.swing.JFrame {
    private PnlPrimerInforme pnlPrimerInforme;
    private PnlSegundoInforme pnlSegundoInforme;
    private PnlTercerInforme pnlTercerInforme;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        
        setSize(700, 400);
        setLocationRelativeTo(null);
        
        pnlPrimerInforme = new PnlPrimerInforme();        
        jPanel1.removeAll();
        jPanel1.add(pnlPrimerInforme);
        jPanel1.revalidate();
        jPanel1.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnPrimerInforme = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnSegundoInforme = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnTercerInforme = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informes - Reto 5");

        jToolBar1.setRollover(true);

        btnPrimerInforme.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrimerInforme.setText("Primer Informe");
        btnPrimerInforme.setFocusable(false);
        btnPrimerInforme.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrimerInforme.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrimerInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimerInformeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPrimerInforme);
        jToolBar1.add(jSeparator1);

        btnSegundoInforme.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSegundoInforme.setText("Segundo Informe");
        btnSegundoInforme.setFocusable(false);
        btnSegundoInforme.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSegundoInforme.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSegundoInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSegundoInformeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSegundoInforme);
        jToolBar1.add(jSeparator2);

        btnTercerInforme.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTercerInforme.setText("Tercer Informe");
        btnTercerInforme.setFocusable(false);
        btnTercerInforme.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTercerInforme.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTercerInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTercerInformeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTercerInforme);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.CardLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimerInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimerInformeActionPerformed
                     
        pnlPrimerInforme = new PnlPrimerInforme();
        showJPanel(pnlPrimerInforme);
    }//GEN-LAST:event_btnPrimerInformeActionPerformed

    private void btnSegundoInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegundoInformeActionPerformed
             
        pnlSegundoInforme = new PnlSegundoInforme();
        showJPanel(pnlSegundoInforme);
    }//GEN-LAST:event_btnSegundoInformeActionPerformed

    private void btnTercerInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTercerInformeActionPerformed
        pnlTercerInforme = new PnlTercerInforme();
        showJPanel(pnlTercerInforme);
    }//GEN-LAST:event_btnTercerInformeActionPerformed

    public void showJPanel(JPanel p){
        jPanel1.removeAll();
        jPanel1.add(p);
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrimerInforme;
    private javax.swing.JButton btnSegundoInforme;
    private javax.swing.JButton btnTercerInforme;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
